#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'2.4.1'


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [16]:
arr.itemsize*arr.size

80

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [18]:
arr=np.zeros(10)
arr[4]=1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [20]:
arr=np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [23]:
arr=arr[::-1]
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [29]:
arr=np.arange(0,9)
arr=arr.reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [32]:
arr=np.array([1,2,0,0,4,0] )
np.nonzero(arr)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [34]:
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [38]:
matrix=np.random.random((3,3))
matrix

array([[0.55052492, 0.58694842, 0.40442006],
       [0.91064756, 0.95737494, 0.11462198],
       [0.53712446, 0.54070873, 0.49003331]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [41]:
matrix=np.random.random((3,3))
matrix.max()
matrix.min()

np.float64(0.10477628903046587)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [44]:
arr=np.random.random(30).mean()
arr

np.float64(0.4366379045215678)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)


In [46]:
arr=np.ones((3,3))
for i in range(len(arr)):
    for j in range(len(arr)):
        if i!=0 and j!=0 and i!=len(arr)-1 and j!=len(arr[0])-1:
            arr[i][j]=0

arr

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [53]:
arr=np.ones((3,3))
padded_array = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
padded_array

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)


In [58]:
arr=np.zeros((5,5),dtype=int)
values=np.array([1,2,3,4])
for i in range(len(values)):
    arr[i+1, i] = values[i]
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)


In [63]:
arr=np.ones((8,8),dtype=int)
for i in range(len(arr)):
    for j in range(len(arr[0])):
        if(i+j)%2==0:
            arr[i][j]=0
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)


In [66]:
arr=np.zeros((6,7,8))
z=100%8
val=100//8
y=val%7
val=val//7
x=val%6
val=val//6
print(x,y,z)

1 5 4


In [67]:
#### 22. Normalize a 5x5 random matrix (★☆☆)

arr=np.random.random((5,5))
arr/arr.sum()

array([[0.05856206, 0.03497078, 0.06056435, 0.05951838, 0.04066579],
       [0.04432385, 0.02738532, 0.03290195, 0.0259425 , 0.05978689],
       [0.03164075, 0.04721867, 0.04026523, 0.03418805, 0.05046395],
       [0.01914596, 0.03953667, 0.03291335, 0.01052022, 0.05026611],
       [0.05973877, 0.05225593, 0.02734428, 0.00181142, 0.05806875]])

In [72]:
#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
data_type=[('red',np.uint8),('green',np.uint8),('blue',np.uint8)]
arr=np.array([1,2,3],dtype=data_type)
np.dtype(arr[0])

dtype([('red', 'u1'), ('green', 'u1'), ('blue', 'u1')])

In [74]:
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

arr1=np.random.random((5,3))
arr2=np.random.random((3,2))
np.matmul(arr1,arr2)

array([[0.38862868, 0.31321542],
       [0.44660823, 0.16268953],
       [0.40857276, 0.35378778],
       [0.36777978, 0.40459413],
       [0.77788424, 0.65532593]])

In [76]:
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

arr=np.arange(0,10)
for i in range(len(arr)):
    if arr[i]>=3 and arr[i]<=8:
        arr[i]=arr[i]*-1

arr

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9])

In [84]:
print(sum(range(5),-1))



10
10


In [87]:
z=np.arange(0,10)
print(z**z)
print(2<<z>>2)
print(z<-z)
print(1j*z)
print(z/1/1)
print(z<z>z)


[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [88]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/90/7bhc4qw17dd0tc8r6137_d040000gn/T/ipykernel_16902/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

In [103]:
#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

from datetime import date, timedelta

# Get today's date
today = date.today()

# Calculate yesterday and tomorrow
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

# Print results
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2026-02-04
Today: 2026-02-05
Tomorrow: 2026-02-06


In [105]:
#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
np.arange('2016-07','2016-08',dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [10]:
#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

arr=np.random.random(5)
print(arr)
arr1=np.floor(arr)
print(arr1)
arr2=arr.astype(int)
print(arr2)
arr3=np.trunc(arr)
print(arr3)

[0.81090537 0.20250746 0.97170386 0.48531048 0.29420312]
[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[0. 0. 0. 0. 0.]


In [11]:
#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

arr=np.zeros((5,5))
values=np.arange(0,5)
arr+=values
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [15]:
#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

def generator():
    return np.random.rand()

arr=[]
for i in range(10):
    arr.append(generator())
print(arr)

[0.7955247768144424, 0.97764975202321, 0.5979746682598535, 0.16924341338835458, 0.3617598706441184, 0.11979380041181653, 0.25647956245943027, 0.6522436083656262, 0.51263846561221, 0.7276309417794891]


In [19]:
#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
arr=np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [21]:
#### 40. Create a random vector of size 10 and sort it (★★☆)
arr=np.random.random(10)
arr=np.sort(arr)
arr

array([0.00749654, 0.08295085, 0.10530625, 0.12313025, 0.15325942,
       0.42967932, 0.50922804, 0.5372971 , 0.71423713, 0.97753138])

In [22]:
#### 41. How to sum a small array faster than np.sum? (★★☆)
arr=np.random.random(10)
print(sum(arr))

3.2317337242254727


In [25]:
#### 42. Consider two random arrays A and B, check if they are equal (★★☆)
a1=np.random.random(10)
a2=np.random.random(10)
np.array_equal(a1,a2)

False

In [29]:
#### 43. Make an array immutable (read-only) (★★☆)
x=np.arange(1,10)
x.flags.writeable = False


In [31]:
#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
cart=np.random.random((10,2))
X=cart[:,0]
Y=cart[:,1]
r=np.sqrt(X**2+Y**2)
theta=np.arctan2(Y,X)
ploar=np.column_stack((r,theta))
ploar


array([[0.98675085, 1.55612624],
       [0.38541363, 1.28373361],
       [0.5369511 , 0.15089635],
       [0.83569856, 0.78466159],
       [0.63169637, 1.53673945],
       [0.90868971, 1.27742614],
       [0.89436221, 1.47463901],
       [0.62006852, 0.37771341],
       [1.00314041, 0.95804316],
       [0.93997749, 0.84283081]])

In [35]:
#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
index=arr.argmax()
arr[index]=0
arr


array([0.20303465, 0.11095312, 0.28194118, 0.17012209, 0.5990466 ,
       0.06790852, 0.07082589, 0.        , 0.73478604, 0.03387362])

In [36]:
#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

a1=np.random.random(10)
a2=np.random.random(10)
mat=np.zeros((10,10))
for i in range(10):
    for j in range(10):
        mat[i][j]=1/(a1[i]-a2[j])
mat

array([[-2.61489995e+00, -2.37322078e+00, -1.67280096e+00,
        -8.61093741e+01,  1.89393897e+01,  4.35692286e+00,
        -2.14895057e+00, -8.28235012e+00, -1.38235216e+00,
        -2.07791946e+00],
       [-1.33987316e+01, -8.80448955e+00, -3.44815846e+00,
         3.37636236e+00,  2.77323360e+00,  1.86112417e+00,
        -6.34704881e+00,  5.34612980e+00, -2.40607417e+00,
        -5.76499365e+00],
       [ 1.01119514e+01,  1.66810146e+01, -8.58493905e+00,
         2.12900243e+00,  1.87225001e+00,  1.40679331e+00,
         6.26045816e+01,  2.77332496e+00, -4.13072974e+00,
         1.51327904e+04],
       [-6.27130645e+01, -1.82182118e+01, -4.32298613e+00,
         2.81797279e+00,  2.38505138e+00,  1.67785811e+00,
        -1.01147775e+01,  4.06935002e+00, -2.80169730e+00,
        -8.71289315e+00],
       [ 6.88192628e+00,  9.40170685e+00, -1.42718930e+01,
         1.93753832e+00,  1.72255801e+00,  1.32056480e+00,
         1.60285834e+01,  2.45704300e+00, -5.11057490e+00,
         2.

In [39]:
#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
arr=np.random.rand(10)
scaler=np.random.rand()
diff=np.abs(arr-scaler)
mini=diff.argmin()
arr[mini]


np.float64(0.6412653619501659)

In [43]:
#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
# import scipy.spatial.distance.cdist(X, X).
arr=np.random.random((10,2))
from scipy.spatial.distance import cdist
distances=cdist(arr,arr)
distances

array([[0.        , 0.49915771, 0.22531787, 0.72549737, 0.50965545,
        0.7528139 , 0.69635923, 0.66449981, 0.68254103, 0.5004946 ],
       [0.49915771, 0.        , 0.29705775, 0.99690607, 0.61793093,
        0.78418883, 0.54605459, 0.56504373, 0.97783279, 0.87385204],
       [0.22531787, 0.29705775, 0.        , 0.75128329, 0.42582248,
        0.64929418, 0.51753323, 0.50062936, 0.72233769, 0.5904478 ],
       [0.72549737, 0.99690607, 0.75128329, 0.        , 0.39874336,
        0.42130572, 0.67210983, 0.60739324, 0.05806948, 0.27069351],
       [0.50965545, 0.61793093, 0.42582248, 0.39874336, 0.        ,
        0.24342078, 0.31320171, 0.25135046, 0.39625626, 0.39764661],
       [0.7528139 , 0.78418883, 0.64929418, 0.42130572, 0.24342078,
        0.        , 0.29809974, 0.24442027, 0.45128978, 0.55419909],
       [0.69635923, 0.54605459, 0.51753323, 0.67210983, 0.31320171,
        0.29809974, 0.        , 0.06507025, 0.68492593, 0.71082501],
       [0.66449981, 0.56504373, 0.5006293

In [50]:
#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

arr=np.random.random(10).astype(np.float32)
arr
arr=arr.view(np.int32)
arr

array([1052082744, 1063351770, 1057342231, 1041000104, 1061246927,
       1057934115, 1060095221, 1056305221, 1038259452, 1057171697],
      dtype=int32)

In [53]:
#### 56. Generate a generic 2D Gaussian-like array (★★☆)

def generate_gau_arr(shape,mu,sigma):
    rows,cols=shape
    X=np.linspace(-1,1,rows)
    Y=np.linspace(-1,1,cols)
    x,y=np.meshgrid(X,Y)
    d=np.sqrt(x*x+y*y)
    g= np.exp(-((d-mu)**2//(2*sigma**2)))
    return g

g=generate_gau_arr((10,10),0.0,1.0)
g
    

array([[0.36787944, 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 0.36787944],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.       

In [55]:
#### 57. How to randomly place p elements in a 2D array? (★★☆)

def put_p_elements(arr,p,value):
    rows,cols=arr.shape
    total_cells = rows * cols
    if p > total_cells:
        raise ValueError("Number of elements to place (p) cannot exceed total cells.")

   
    arr = np.zeros((rows, cols), dtype=int)

    
    flat_indices = np.arange(total_cells)
    
    
    chosen_flat_indices = np.random.choice(flat_indices, p, replace=False)

    
    chosen_rows, chosen_cols = np.unravel_index(chosen_flat_indices, arr.shape)

   
    arr[chosen_rows, chosen_cols] = value
    return arr

arr=np.random.random((10,10))
arr=put_p_elements(arr,5,1)
arr


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]])

In [57]:
#### 59. How to sort an array by the nth column? (★★☆)
a1=np.random.random((10,10))
col=4
print(a1)
a1 = a1[a1[:, col].argsort()]
print(a1)

[[0.88146822 0.30853152 0.16889201 0.74738486 0.47020635 0.01764075
  0.24116651 0.0629311  0.16845    0.01985531]
 [0.46439509 0.78559668 0.66720205 0.48252187 0.78509248 0.53979042
  0.09410966 0.3217021  0.09888585 0.10835054]
 [0.53019163 0.30774037 0.15978733 0.85446118 0.78771843 0.55607931
  0.93936581 0.09347096 0.73381648 0.38762396]
 [0.27698648 0.04775383 0.28538012 0.48343131 0.4396408  0.21792464
  0.19962906 0.43287528 0.52824481 0.57127301]
 [0.08474662 0.35941269 0.81919862 0.02019799 0.41190703 0.81530061
  0.05673582 0.54234168 0.78467488 0.2627062 ]
 [0.25243114 0.71290897 0.65281423 0.63264466 0.41954378 0.44361688
  0.7364526  0.66815791 0.64217712 0.64449491]
 [0.69136111 0.05812769 0.42046208 0.06790118 0.23009052 0.45089761
  0.45441864 0.63285905 0.8089542  0.07596863]
 [0.55545185 0.21976244 0.39246434 0.68438305 0.18533509 0.55849663
  0.74637213 0.90157213 0.10900827 0.59978272]
 [0.39936665 0.98212301 0.24774994 0.27729349 0.49780407 0.81220903
  0.09344407

In [64]:
#### 60. How to tell if a given 2D array has null columns? (★★☆)
arr=np.array([1,np.nan,2])
np.isnan(arr)

array([False,  True, False])

In [66]:
#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

a1=np.random.random((1,3))
a2=np.random.random((3,1))
it = np.nditer([a1, a2, None])
for x, y, z in it:
    z[...] = x + y
result = it.operands[2]
result

array([[0.77064277, 1.2050757 , 0.93952363],
       [1.05724378, 1.49167672, 1.22612465],
       [0.69365497, 1.12808791, 0.86253584]])

In [68]:
#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

a1=np.random.random(10)
print(a1)
index=np.array([1,3,4,5,6])
np.add.at(a1,index,1)
a1

[0.03565419 0.33887069 0.37483263 0.28071253 0.55495794 0.54343634
 0.57117019 0.30530507 0.12442566 0.04889557]


array([0.03565419, 1.33887069, 0.37483263, 1.28071253, 1.55495794,
       1.54343634, 1.57117019, 0.30530507, 0.12442566, 0.04889557])

In [73]:
#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
arr=np.random.random((5,5,3))
arr=arr.reshape((-1,3))
arr=np.unique(arr,axis=0)
len(arr)

25

In [75]:
#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

arr_4d = np.arange(120).reshape((2, 3, 4, 5))
np.sum(arr_4d, axis=(2, 3))

array([[ 190,  590,  990],
       [1390, 1790, 2190]])

In [77]:
original_vector = np.array([1, 2, 3, 4, 5])
n = len(original_vector)
zeros_count = 3
new_size = n * (zeros_count + 1)
new_vector = np.zeros(new_size, dtype=original_vector.dtype)
new_vector[::zeros_count + 1] = original_vector
new_vector
#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)


array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0])

In [79]:
#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

A = np.random.rand(5, 5, 3)

B = np.random.rand(3)
A@B


array([[0.7039754 , 1.03504435, 0.77715024, 0.44066664, 1.08231996],
       [0.56859479, 0.49485962, 0.64449628, 0.6826378 , 1.03396693],
       [0.81598677, 0.89436302, 0.73018871, 0.60055668, 0.79719106],
       [0.48217395, 0.18808329, 0.20719641, 0.40114672, 0.82868455],
       [0.57406217, 0.71450303, 1.13577532, 0.80700605, 0.56322413]])

In [85]:
#### 82. Compute a matrix rank (★★★)
# Create a 3x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(np.sum(matrix))
rank = np.linalg.matrix_rank(matrix)
rank

45


np.int64(2)

In [84]:
arr=np.array([1,2,4,3,2,3,2,3,2])
counts = np.bincount(arr)
np.argmax(counts)

np.int64(2)

In [86]:

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)


A = np.array([
    [1, 2, 3],
    [3, 4, 5],
    [2, 1, 4],
    [6, 7, 8],
    [1, 3, 5],
    [2, 4, 6],
    [3, 1, 2],
    [4, 5, 6]
])

B = np.array([
    [1, 2],
    [4, 5]
])

mask = np.any(
    np.all(np.isin(A[:, None, :], B), axis=2),
    axis=1
)

result = A[mask]
print(result)


[[2 1 4]]
